version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
    timezone: America/New_York
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.2
