dist: xenial
language: python
python: 3.7
env:
  global:
    - VERSION=$TRAVIS_TAG

addons:
  apt:
    packages:
    - afflib-tools
    - archivemount
    - avfs
    - cryptsetup
    - disktype
    - exfat-fuse
    - exfat-utils
    - libguestfs-tools
    - libvshadow-utils
    - lvm2
    - mdadm
    - mtd-utils
    - ocfs2-tools
    - open-vm-tools
    - qemu-utils
    - sleuthkit
    - sqlite3
    - squashfs-tools
    - vmfs-tools
    - xfsprogs
    - xmount
    - zlib1g-dev

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - cd tests
  - python download-test-images.py --dftt
  - sudo -E /home/travis/virtualenv/python3.7/bin/pytest
  - cd ..
  - python setup.py sdist bdist_wheel

deploy:
  - provider: releases
    api_key:
      secure: "mwzWHORvlkJ05LrC+Cxe/usyESrmUIQqXe6do9mxu7GPDiSKJDUJ1Wu2fOmSOFzPMnurITdhVK8FCXzukaymi6M0keescxxhdTvGVzzutJl5A4IF6jj4kge2LZ3tBzz+iJKMq9+FApzaMV8ltftt5/Iw6gP7HTp0qH/6w0VXVuWdlAm12WKMbC8fX6oVKWluDJMQNT2lsXgK3ZQvjW+5DvfE5eA9BCwIym8S44N8ytPNyDPOvOAQNJd6IiLETu0qNJuEOFX6akiT/hfGvycCeaM9YrE7nozNwguH0GaV30L6BQ7KmlWokPeh3MXcHXQEE2F4DIgrajzxd3lb0UroQ5WgHxDAI1JQcajwSUM5tsE4mznSPPwrjmyg+CYw05SPE28BjjYr2OJEZfOCVdEEBxrXuzeh01GVCsD3WRNcEQVnjJT+eSjRgqlpq7+/fK/kaevKeKIlYZmJxFyIpb1wQk4aIfCvLrpw883Qcz2MYrpV3qMpMb+9fCW5/8cDb5ioqqRLqqiAOeWrhWhPft7jNN4axQC3czwsJOrUCsUouAw7Xo+fTO+XiyDQHeLMiGzbdWiZ4Ch7g/0LP3f45KTF9U7QsR8miJSrVJzVaNgdKOntTvPFQkT5KAcaoTDfOrb/uMwFqljXFg1zfsBcGxe01j45C1GxECrcQwgDDiN0g6s="
    file:
      - dist/thumbtack-$VERSION.tar.gz
      - dist/thumbtack-$VERSION-py2.py3-none-any.whl
    skip_cleanup: true
    on:
      tags: true
  - provider: pypi
    user: __token__
    password:
      secure: "m8YipMgALvXeSVChDKZVH0zJZaTqzqZMZMASFu7Ha+TcSy3oBi2ueq3CcwXPT50/zPsiaDQWwHKt83LwMbWEqALzb460tMfYAJiK1a165KVpeajOT2u9XqxtyJjkblp8S6v7g2y3Fap6dfcEJoR6H9XDZS4UraoDUG3AeRQ6Uu+3nUT1P9sYflKd4aj23arAsQsdrAORpbP9FWUekwlPORLdHJPTX+4l3B7yo+NxRXCqQsfmlj08eRdJRugek//3/ihEa+yuW0O2uRYNvY2jPN+fFF4fTZbqO/O28B4TL5iQFRsP8rbrtm9U0nWDuHbAJ6NVJSIIGV2Dy6jRrbmHr0+zGIKB18bC9mU39vDpeaK9YSKZQ4eBTGIQRTMUJ0S6+330hLcuzKL597gaDy3nY6/BHfCWr7nqbCReo53KoDRLkG1Rfhh6sAh43R3G1A2B7mHY12bfgrQruCXf1PWj3ZXQumEXOfIdaZaWsAYjX0zVnKRkRtp/+FGrFURHzv0WYWLjjAeHPkAEWjVZiHVFSxKjxHDClhpV69qKd8VQnBkJrkS42+Sj2abWI8PhfVjNnevgawSZm7rveTy4VI/vsWTmrTGZdnGrspkf9CYlTw3LkLzMUkaADyIg8US03iJFfAKnRN9YF5qPxbW/3b64WskYaOgstlYaPSY4xL6MFng="
    skip_cleanup: true
    on:
      tags: true

