name: thumbtack-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install apt dependencies
        run: apt update && apt-get install afflib-tools archivemount avfs cryptsetup disktype exfat-fuse exfat-utils libguestfs-tools libvshadow-utils lvm2 mdadm mtd-utils ocfs2-tools open-vm-tools qemu-utils sleuthkit sqlite3 squashfs-tools vmfs-tools xfsprogs xmount zlib1g-dev
      - name: pip install
        run: pip install -r requirements.txt
        run: pip install -e . 
